### ISSUE TITLE
To Do (Server side) Checklist

### ISSUE THREAD

**Issue by shukikat** [shannonMG/LaxStats#7]
**I many of these are done, Will create Issues for those that still need work**

- [x]  Create User (coach OR player) 
- [ ] Player user only has access to their practices (frontend)
- [x] Login functionality-assign token with valid credentials, cannot log in when credentials are invalid
- [x] Add New Practice (document created in base) 
- [x] Update player stats within practice
- [ ] Query for all practices 
- [ ] Query for singular practice
- [x] Update Completed Balls stat (associated with player and practice)
- [x] Update dropped ball stat (associated with player and practice) 
- [ ] Do we need to add something on the back end to ensure player stats are reset at log out or is that totally front end?
- [ ] Query for Single Practice /average stats for whole team?
